name: "CI"

# Controls when the action will run.
on:
  push:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/catfood.yml'
  pull_request:
    paths:
      - '*.kicad_sch'
      - '*.kicad_pcb'
      - '*.kibot.yaml'
      - '.github/workflows/catfood.yml'
  repository_dispatch:
    types: [run_gha]

jobs:
  ERC:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Run ERC
      uses: INTI-CMNB/KiBot@v2_k7
      with:
        dir: Generated
        skip: run_drc
        targets: __NONE__

    - name: Retrieve results
      uses: actions/upload-artifact@v3
      with:
        name: ERC_Output
        path: Generated


#  DRC:
#    runs-on: ubuntu-latest
#    needs: ERC
#
#    steps:
#    - uses: actions/checkout@v3
#      with:
#        fetch-depth: 0
#
#    - name: Run DRC
#      uses: INTI-CMNB/KiBot@v2_k7
#      with:
#        dir: Generated
#        skip: run_erc
#        targets: __NONE__
#
#    - name: Retrieve results
#      uses: actions/upload-artifact@v3
#      with:
#        name: DRC_Output
#        path: Generated


  default:
    name: "Default variant"
    runs-on: ubuntu-latest
#    needs: [ERC, DRC]
    needs: [ERC]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: INTI-CMNB/KiBot@v2_k7
      with:
        dir: default
        skip: run_erc,run_drc

    - name: upload results
      uses: actions/upload-artifact@v3
      with:
        name: default_variant
        path: default
